version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: weekly

      groups:
        opentelemetry:
          patterns: ["@opentelemetry/*"]
        dev-deps:
          dependency-type: development

      ignore:
      # Packages requiring NodeJS 18+
      - dependency-name: 'urlpattern-polyfill'
        versions:
        - '>= 9'
